---
title: "Farmscale study ML"
author: "Josepha Schiller"
date: "2025-04-02"
output: html_document
---

```{r}
# Project: crossDiv
# Aim of script: Model training and comparison + XAI application
# Note: This script is based on Ryo 2022 and Schiller et al. 2024

# Date of first version: 08.10.2024
# Last update: 2.4.2025

# Please note that some important lines have been commented out to avoid time intense computations or overwrite existing files. 
```

```{r, warning=FALSE}
# Load required libraries
library(tidyverse)
library(gridExtra)
library(caret)
library(pdp)
library(vip)
library(iml)
library(cowplot)
library(openair)
```


```{r}
# Display session info for reproducibility
sessionInfo()
```


```{r}
# Load and preprocess data
setwd("D:/Josi/PhD/CrossDIV/WP1.2_Method/WP1.2_Method_Data/R Scripts/4_IACS_Betriebe_exploration/output_files")
df <- read.table(file = "ML_dataset_20241028.csv", header = TRUE, sep = ",")
```


```{r}
# adjust area to hectares
total_ha <- 10*10
df <- df %>% 
  na.omit() %>%
  mutate(mean_temp = mean_temp / 10) %>%  # Adjust temperature to real values
  dplyr::select(-c(X, id, DGM_min, DGM_max))  %>% # Remove irrelevant columns
  mutate(Farm_size_mean_ha = Farm_size_mean / 10000,
         Field_area_ha = Field_area/10000,
         ha_per_crop = Field_area_ha / crop_sp_rich,
         Field_size_mean_ha = Field_size_mean /10000,
         Prop_oko_ha = Area_oeko / Field_area)
```


```{r}
# Create ML_output directory and subdirectories if they don't exist
dir.create("ML_output_20241030", showWarnings = FALSE)
dir.create("ML_output_20241030/csv", showWarnings = FALSE)
dir.create("ML_output_20241030/png", showWarnings = FALSE)
```


```{r}
# Summarize and save dataset info
getwd()
summary_df <- summary(df)
```


```{r}
#setwd("D:/Josi/PhD/CrossDIV/WP1.2_Method/WP1.2_Method_Data/R Scripts/4_IACS_Betriebe_exploration/output_files/ML_output_20241030")
#write.csv(summary_df, file = file.path("csv", paste0(format(Sys.Date(), "%Y%m%d"), "_df_sum.csv")))  # For Appendix
```


```{r}
# Visualize spatial coverage
spatial_coverage <- ggplot(df, aes(x = x_coord, y = y_coord)) + 
  geom_point()

# save it
#ggsave(file.path("png", "spatial_coverage.png"), plot = spatial_coverage, width = 10, height = 8, dpi = 300)
```


```{r}
# Create and save correlation heatmap

# compute pearson's r
cor_matrix <- cor(df)
```


```{r}
# change format to plot later
cor_melted <- reshape2::melt(cor_matrix) %>%
  filter(as.integer(Var1) <= as.integer(Var2))
```


```{r}
# round pearson's r valus
cor_melted$value <- round(cor_melted$value, 2)
```


```{r}
# save for Appendix
#setwd("D:/Josi/PhD/CrossDIV/WP1.2_Method/WP1.2_Method_Data/R Scripts/4_IACS_Betriebe_exploration/output_files/ML_output_20241030")
#write.csv(cor_melted, file = file.path("csv", paste0(format(Sys.Date(), "%Y%m%d"), "_correlation_matrix.csv")))  # For Appendix
```


```{r, fig.height= 20, fig.width=20}
# plot text when r >= 0.7 
# identifying collinearity to avoid using highly correlated variables in models
p <- ggplot(cor_melted, aes(x = Var1, y = Var2, fill = value)) +
  geom_tile() +
  geom_text(aes(label = ifelse(abs(value) >= 0.7, round(value, 2), "")), 
            color = "black", size = 2.5) +
  scale_fill_gradient2(low = "blue", high = "red", mid = "white", 
                       midpoint = 0, limit = c(-1,1), space = "Lab", 
                       name = "Pearson's\nCorrelation") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1),
        panel.background = element_rect(fill = "white", color = NA),
        plot.background = element_rect(fill = "white", color = NA)) +
  coord_fixed() +
  labs(x = "", y = "", title = "Correlation Heatmap of Variables (|r| >= 0.7)") +
  scale_x_discrete(limits = rev(levels(cor_melted$Var1))) +
  scale_y_discrete(limits = levels(cor_melted$Var2))

p

setwd("D:/Josi/PhD/CrossDIV/WP1.2_Method/WP1.2_Method_Data/R Scripts/4_IACS_Betriebe_exploration/output_files/ML_output_20241030")
#ggsave(file.path("png", "20250405_correlation_heatmap.png"), plot = p, width = 12, height = 10, dpi = 1200, bg = "white")
```


```{r}
# plot text when r >= 0.2
# provide comprehensive overview for appendix
p2 <- ggplot(cor_melted, aes(x = Var1, y = Var2, fill = value)) +
  geom_tile() +
  geom_text(aes(label = ifelse(abs(value) >= 0.2, round(value, 2), "")), 
            color = "black", size = 2) +
  scale_fill_gradient2(low = "blue", high = "red", mid = "white", 
                       midpoint = 0, limit = c(-1,1), space = "Lab", 
                       name = "Pearson's\nCorrelation") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1),
        panel.background = element_rect(fill = "white", color = NA),
        plot.background = element_rect(fill = "white", color = NA)) +
  coord_fixed() +
  labs(x = "", y = "", title = "Correlation Heatmap of Variables (|r| >= 0.2)") +
  scale_x_discrete(limits = rev(levels(cor_melted$Var1))) +
  scale_y_discrete(limits = levels(cor_melted$Var2))

#ggsave(file.path("png", "correlation_heatmap_2.png"), plot = p2, width = 12, height = 10, dpi = 300, bg = "white")
```


```{r}
# Create scatter plots for crop richness and diversity relationships
# Calculate correlations
cor1 <- cor(df$crop_rot_rich, df$crop_sp_rich, method = "pearson")
cor2 <- cor(df$crop_rot_SDI, df$crop_sp_SDI, method = "pearson")
```


```{r}
p1 <- ggplot(df, aes(x = crop_rot_rich, y = crop_sp_rich)) +
  geom_point(alpha = 0.5, size = 2) +
  geom_smooth(method = "lm", color = "red", se = FALSE) +
  theme_minimal() +
  theme(panel.background = element_rect(fill = "white", color = NA),
        plot.background = element_rect(fill = "white", color = NA),
        axis.title = element_text(size = 28),
        axis.text = element_text(size = 20),
        plot.title = element_text(size = 30)) +
  labs(x = "Crops in Time", 
       y = "Crops in Space",
       title = "Richness") +
  annotate("text", x = Inf, y = -Inf, 
           label = sprintf("r = %.2f", cor1),
           hjust = 1.1, vjust = -0.5,
           size = 15)

p2 <- ggplot(df, aes(x = crop_rot_SDI, y = crop_sp_SDI)) +
  geom_point(alpha = 0.5, size = 2) +
  geom_smooth(method = "lm", color = "red", se = F) +
  theme_minimal() +
  theme(panel.background = element_rect(fill = "white", color = NA),
        plot.background = element_rect(fill = "white", color = NA),
        axis.title = element_text(size = 28),
        axis.text = element_text(size = 20),
        plot.title = element_text(size = 30)) +
  labs(x = "Crops in Time", 
       y = "Crops in Space",
       title = "Shannon's Diversity") +
  annotate("text", x = Inf, y = -Inf, 
           label = sprintf("r = %.2f", cor2),
           hjust = 1.1, vjust = -0.5,
           size = 15)

# Arrange plots side by side and save
combined_plot <- plot_grid(p1, p2, ncol = 2, labels = c("A", "B"), label_size = 30)
combined_plot
```


```{r, eval = F}
# Save as PNG
#ggsave(file.path("png", "crop_diversity_relationships.png"), 
#       plot = combined_plot, width = 12, height = 7, dpi = 1200, bg = "white")

# Save as PDF 
#ggsave(file.path("png", "crop_diversity_relationships.pdf"), 
#       plot = combined_plot, width = 12, height = 7, bg = "white")
```


```{r}
# Create a directory for spatial plots if it doesn't exist
dir.create("spatial_plots", showWarnings = FALSE)
```


```{r}
# Get current date
current_date <- format(Sys.Date(), "%Y%m%d")
```


```{r}
# Function to create and save combined spatial plot
create_combined_spatial_plot <- function(data, var_names) {
  plots <- lapply(var_names, function(var_name) {
    var_min <- min(data[[var_name]], na.rm = TRUE)
    var_max <- max(data[[var_name]], na.rm = TRUE)
    ggplot(data, aes(x = x_coord, y = y_coord)) +
      geom_point(aes(color = .data[[var_name]]), alpha = 0.7) +
      scale_color_viridis_c(option = "plasma", 
                            limits = c(var_min, var_max),
                            labels = scales::label_number(accuracy = 0.01),
                            name = paste0(var_name, "\n(", round(var_min, 2), " to ", round(var_max, 2), ")")) +
      theme_minimal() +
      labs(title = var_name,
           x = "X Coordinate", 
           y = "Y Coordinate") +
      theme(legend.position = "right",
            panel.background = element_rect(fill = "white", color = NA),
            plot.background = element_rect(fill = "white", color = NA))
  })
  combined_plot <- gridExtra::grid.arrange(grobs = plots, ncol = 2)
  
#  filename <- paste0(current_date, "_spatial_plot_", paste(var_names, collapse = "_"), ".png")
#  ggsave(filename = file.path("spatial_plots", filename), 
#         plot = combined_plot, 
#         width = 15, 
#         height = 10, 
#         dpi = 300)
}
```


```{r}
# Group similar variables
variable_groups <- list(
  c("cropPC1", "cropPC2"),
  c("crop_f_rich", "crop_f_SDI"),
  c("crop_sp_rich", "crop_sp_SDI", "ha_per_crop"),
  c("crop_rot_rich", "crop_rot_SDI"),
  c("livestock_f_SDI", "livestock_f_SEI", "livestock_f_rich"),
  c("habitat_SDI", "habitat_RICHNESS", "habitat_EDGE_DENSITY"),
  c("Area_oeko_log1p", "Area_oeko","Number_l_farms_log10", "Number_okeo_farm_log1p"),
  c("mean_temp", "mean_prec", "DGM_range", "SQR_mean"),
  c("prop_livestock_farms", "prop_oeko_farms"),
  c("Farm_size_mean", "Farm_size_median", "Field_size_mean", "Field_size_median")
)
```


```{r}
# Create combined spatial plots for grouped variables
for (group in variable_groups) {
  create_combined_spatial_plot(df, group)
}
```


```{r}
# Create individual plots for remaining variables
remaining_vars <- setdiff(names(df), c("x_coord", "y_coord", unlist(variable_groups)))
for (var in remaining_vars) {
  create_combined_spatial_plot(df, c(var))
}
```


```{r}
# Remove collinear variables for modeling
df_model <- df %>% 
  dplyr::select(-c(Area_oeko_log1p, Area_oeko, #because of similarity with Area_oeko
            crop_f_SEI, crop_f_rich, #because of similarity with crop_f
            Farm_size_median, Farm_size_mean_log10, Farm_size_mean, #related to farm size
            Field_size_median, Field_size_mean_log10, Field_size_mean, #related to field size
            Field_area, #related to field metrics
            habitat_SEI, habitat_SDI, #because of similarity with habitat_RICHNESS
            livestock_f_SEI, livestock_f_rich, #because of similarity with livestock_f_SDI
            mean_prec, mean_temp, #climate variables
            Number_fields_log10, #field count
            Number_l_farms_log10, Number_okeo_farm_log1p #related to farm counts
         ))

df_model %>% head()
```


```{r}
summary(df_model)
```


```{r, fig.height= 20, fig.width=20}
# Create and save correlation heatmap for model variables
cor_matrix_model <- cor(df_model, use = "pairwise.complete.obs")
p_model <- ggplot(data = reshape2::melt(cor_matrix_model), aes(x = Var1, y = Var2, fill = value)) +
  geom_tile(color = "white") +
  scale_fill_gradient2(low = "blue", high = "red", mid = "white", 
                       midpoint = 0, limit = c(-1,1), space = "Lab", 
                       name = "Pearson\nCorrelation") +
  geom_text(aes(label = ifelse(abs(value) >= 0.7, sprintf("%.2f", value), "")), 
            color = "black", size =4) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1),
        panel.background = element_rect(fill = "white", color = NA),
        plot.background = element_rect(fill = "white", color = NA)) +
  coord_fixed() +
  labs(title = "Correlation Heatmap of Model Variables", x = "", y = "")

p_model
#ggsave(file.path("png", "correlation_heatmap_model_variables.png"), plot = p_model, width = 12, height = 10, dpi = 1200)
```


```{r}
# Generate random seeds for reproducibility
set.seed(40)
random_numbers <- sample(1:100, 10)
```


```{r}
# Prepare training and test datasets
data_train_list <- list()
data_test_list <- list()
```


```{r}
for (i in seq_along(random_numbers)) {
  set.seed(random_numbers[i])
  train_indices <- sample(1:nrow(df_model), 0.7 * nrow(df_model), replace = FALSE)
  data_train_list[[i]] <- df_model[train_indices, ]
  data_test_list[[i]] <- df_model[-train_indices, ]
}
```


```{r}
# Apply summary to training and test datasets
summary_train <- lapply(data_train_list, summary)
summary_test <- lapply(data_test_list, summary)
```


```{r}
# Display summaries for the first two iterations
print(summary_train[[1]])
print(summary_test[[2]])
```


```{r}
# Display number of observations in each split
splitdf <- data.frame(
  dataset = rep(c("training", "test"), each = length(data_train_list)),
  iteration = rep(1:length(data_train_list), 2),
  n = c(sapply(data_train_list, nrow), sapply(data_test_list, nrow))
)
splitdf
```


```{r, eval = F}

# Save split information
#write.csv(splitdf, file = file.path("csv", "data_split_info.csv"), row.names = FALSE)
```


```{r}
# Define resampling method for model training
tc <- trainControl(method = "cv", number = 5)  # 5-fold cross-validation
```


```{r}
# Define model formulas
formula_list <- list(
  formula1 = cropPC1 ~ . - crop_rot_SDI - crop_rot_rich- crop_sp_SDI - crop_sp_rich -cropPC2  - Prop_oko_ha  -Field_area_ha,
  formula2 = cropPC2  ~ . - crop_rot_SDI - crop_rot_rich- crop_sp_SDI - crop_sp_rich  - Prop_oko_ha  -Field_area_ha - cropPC1,
  formula3 = crop_rot_rich ~ . - Prop_oko_ha -cropPC2 -cropPC1 -Field_area_ha -crop_rot_SDI -crop_sp_rich,
  formula4 = crop_rot_SDI ~ . - Prop_oko_ha -cropPC2 -cropPC1 -Field_area_ha - crop_rot_rich -crop_sp_rich,
  formula5 = crop_sp_rich ~ . - Prop_oko_ha -cropPC2 -cropPC1 -Field_area_ha - crop_sp_SDI -crop_rot_rich,
  formula6 = crop_sp_SDI ~ .  - Prop_oko_ha -cropPC2 -cropPC1  -Field_area_ha - crop_sp_rich -crop_rot_rich
 )
```

Function to train models with different algorithms
```{r}
# write function fpr model training with different algorithms 

train_models <- function(formula_nr, data_train, tc) {
  # lm
  set.seed(123)
  model.lm <- caret::train(formula_nr, data = data_train, method = "glmStepAIC", trControl = tc)
  
  # decision tree
  set.seed(123)
  model.cart <- caret::train(formula_nr, data = data_train, method = "ctree", trControl = tc)
  
  # random forest
  set.seed(123)
  model.rf <- caret::train(formula_nr, data = data_train, method = "rf", trControl = tc) #randomForest package
  
  # gradient boosting
  set.seed(123)
  model.gbm <- caret::train(formula_nr, data = data_train, method = "gbm", trControl = tc,
                            tuneGrid = expand.grid(n.trees = (1:5) * 500, interaction.depth = (1:5) * 3,
                                                   shrinkage = 0.1, n.minobsinnode = 10)) 
  
  # Rückgabe der trainierten Modelle
  list(model.lm = model.lm, model.cart = model.cart, model.rf = model.rf, model.gbm = model.gbm)
}
```


```{r}
crop_models_list2 <- list()

#for (i in 1:length(data_train_list)) {
#  crop_models <- list()
  
#  for (j in 1:length(formula_list)) {
#    formula_name <- names(formula_list)[j]
#    crop_models[[formula_name]] <- train_models(formula_list[[j]], data_train_list[[i]], tc)
#  }
  
#  crop_models_list2[[i]] <- crop_models
#}
# Save trained models with date
#training_date <- format(Sys.time(), "%Y-%m-%d")
#saveRDS(list(models = crop_models_list2, date = training_date), 
#        file = file.path(paste0("trained_models_", training_date, ".rds")))
```


```{r}
# Load saved models
setwd("D:/Josi/PhD/CrossDIV/WP1.2_Method/WP1.2_Method_Data/R Scripts/4_IACS_Betriebe_exploration/output_files/ML_output_20241030")
loaded_models <- readRDS(file.path(paste0("trained_models_2024-11-04.rds")))
crop_models_list2 <- loaded_models$models
model_training_date <- loaded_models$date

crop_models_list2[[1]]$formula6$model.lm$coefnames

crop_models_list <- crop_models_list2
```


```{r}
# Function to get R-squared values for trained models
get_train_r2 <- function(crop_models_list, formula_name) {
  r2_values <- list(
    GLM_R2 = numeric(length(crop_models_list)),
    CART_R2 = numeric(length(crop_models_list)),
    RF_R2 = numeric(length(crop_models_list)),
    GBM_R2 = numeric(length(crop_models_list))
  )
  
  for (i in seq_along(crop_models_list)) {
    r2_values$GLM_R2[i] <- crop_models_list[[i]][[formula_name]]$model.lm$results$Rsquared
    
    sel_hyper_CART <- crop_models_list[[i]][[formula_name]]$model.cart$bestTune$mincriterion
    r2_values$CART_R2[i] <- crop_models_list[[i]][[formula_name]]$model.cart$results %>% 
      filter(mincriterion == sel_hyper_CART) %>% 
      pull(Rsquared)
    
    sel_hyper_RF <- crop_models_list[[i]][[formula_name]]$model.rf$bestTune$mtry
    r2_values$RF_R2[i] <- crop_models_list[[i]][[formula_name]]$model.rf$results %>% 
      filter(mtry == sel_hyper_RF) %>% 
      pull(Rsquared)
    
    sel_hyper_GBM <- crop_models_list[[i]][[formula_name]]$model.gbm$bestTune
    r2_values$GBM_R2[i] <- crop_models_list[[i]][[formula_name]]$model.gbm$results %>% 
      inner_join(sel_hyper_GBM, by = c("n.trees", "interaction.depth", "shrinkage", "n.minobsinnode")) %>% 
      pull(Rsquared)
  }
  
  return(r2_values)
}
```


```{r}
# List of algorithms and formulas
algorithms <- c("model.lm", "model.cart", "model.rf", "model.gbm")
formulas <- c("formula1", "formula2", "formula3", "formula4", "formula5", "formula6")
```


```{r}
# Calculate mean and standard deviation of R-squared for each algorithm and formula based on training data
train_results_list <- lapply(formulas, function(formula) {
  r2_values <- get_train_r2(crop_models_list, formula)
  data.frame(
    Formula = formula,
    Algorithm = algorithms,
    train_mean_r2 = sapply(r2_values, mean),
    train_sd_r2 = sapply(r2_values, sd)
  )
})
```


```{r}
# Combine all training results into a single data frame
train_comparison_df <- do.call(rbind, train_results_list)

train_R2_df <- train_comparison_df %>%
  mutate(
    train_r2 = paste(round(train_mean_r2, 2), "±", round(train_sd_r2, 2)),
  ) %>%
  pivot_wider(
    id_cols = Formula,
    names_from = Algorithm,
    values_from = c(train_r2),
    names_prefix = "train_"
  )

#write.csv(train_R2_df, file = file.path("csv", paste0(format(Sys.Date(), "%Y%m%d"), "_train_performance.csv")), row.names = FALSE)
```


```{r}
# Function to compute R-squared, MAE, and Pearson's correlation for test data
compute_test_metrics <- function(model, test_data, response_var) {
  predictions <- predict(model, newdata = test_data)
  actual <- test_data[[response_var]]
  
  SST <- sum((actual - mean(actual))^2)
  SSE <- sum((actual - predictions)^2)
  
 # r_squared <- 1 - SSE / SST
  mae <- mean(abs(actual - predictions))
  pearson_cor <- cor(actual, predictions, method = "pearson")
  r_squared <- cor(actual, predictions, method = "pearson")^2
  
  list(r_squared = r_squared, mae = mae, pearson_cor = pearson_cor)
}
```


```{r}
# Initialize lists to store metrics for each algorithm and formula
test_metrics <- list()
formula_list
```


```{r}
# define response variables
response_vars <- list(
  formula1 = "cropPC1",
  formula2 = "cropPC2",
  formula3 = "crop_rot_rich",
  formula4 = "crop_rot_SDI",
  formula5 = "crop_sp_rich",
  formula6 = "crop_sp_SDI"
)
```


```{r, warning=F}
# Loop through formulas and algorithms to compute metrics
for (formula in formulas) { #selects formulas
  for (alg in algorithms) { #selects algorithms
    metrics <- lapply(1:10, function(i) {
      model <- crop_models_list[[i]][[formula]][[which(algorithms == alg)]]
      test_data <- data_test_list[[i]]
      response_var <- response_vars[[formula]]
      compute_test_metrics(model, test_data, response_var)
    })
    
    test_metrics[[paste(formula, alg, sep = "_")]] <- list(
      r_squared = sapply(metrics, `[[`, "r_squared"),
      mae = sapply(metrics, `[[`, "mae"),
      pearson_cor = sapply(metrics, `[[`, "pearson_cor")
    )
  }
}
```


```{r}
# Calculate average and standard deviation of metrics
test_comparison_df <- do.call(rbind, lapply(names(test_metrics), function(name) {
  formula <- sub("_.*", "", name)
  alg <- sub(".*_", "", name)
  data.frame(
    Formula = formula,
    Algorithm = alg,
    test_mean_r2 = mean(test_metrics[[name]]$r_squared),
    test_sd_r2 = sd(test_metrics[[name]]$r_squared),
    test_mean_mae = mean(test_metrics[[name]]$mae),
    test_sd_mae = sd(test_metrics[[name]]$mae),
    test_mean_pearson = mean(test_metrics[[name]]$pearson_cor),
    test_sd_pearson = sd(test_metrics[[name]]$pearson_cor)
  )
}))
```


```{r}
# Sort the test comparison dataframe in descending order of mean R-squared
test_comparison_df <- test_comparison_df[order(test_comparison_df$test_mean_r2, decreasing = TRUE), ]
```


```{r}
# Reset row names
rownames(test_comparison_df) <- NULL
```


```{r}
# Print the test comparison dataframe
print(test_comparison_df)
```


```{r}
# Save the test comparison dataframe
test_df <- test_comparison_df %>%
  pivot_wider(
    id_cols = Algorithm,
    names_from = Formula,
    values_from = c(test_mean_r2, test_sd_r2, test_mean_mae, test_sd_mae, test_mean_pearson, test_sd_pearson),
    names_glue = "{Formula}_{.value}"
  ) %>%
  arrange(desc(formula1_test_mean_r2))# %>%

test_df 

#write.csv(test_df, file = file.path("csv", paste0(format(Sys.Date(), "%Y%m%d"), "_test_performance.csv")), row.names = FALSE)
```


```{r}
# alternative way
test_R2_df <- test_comparison_df %>%
  mutate(
    test_r2 = paste(round(test_mean_r2, 2), "±", round(test_sd_r2, 2)),
  ) %>%
  pivot_wider(
    id_cols = Formula,
    names_from = Algorithm,
    values_from = c(test_r2),
    names_prefix = "test_"
  )
```


```{r}
# combine test and train R2
# Merge test and train R2 dataframes by Formula
combined_R2_df <- merge(test_R2_df, train_R2_df, by = "Formula") %>%
  dplyr::select(Formula, train_model.lm, test_model.lm, 
                        train_model.cart, test_model.cart, 
                        train_model.rf, test_model.rf, 
                        train_model.gbm, test_model.gbm)

# Print the combined dataframe
print(combined_R2_df)
```


```{r}
# Save the combined R2 dataframe for manuscript
#write.csv(combined_R2_df, file = file.path("csv", paste0(format(Sys.Date(), "%Y%m%d"), "_combined_R2_performance.csv")), row.names = FALSE)
```


```{r}
# APPLY XAI

test_metrics
```


```{r}
# Function to create VIP plots
vip_plots <- function(my_model, my_responsevar, my_title){
  
  # Single plots 
  set.seed(123)
  pvip_lm <- vip(my_model[[1]], method="permute", train=data_train_list[[1]], target= my_responsevar, 
                 metric="rsq", pred_wrapper=predict, 
                 nsim=30, geom="boxplot",
                 aesthetics = list(fill = "grey", color="black")) + 
    labs(title="Linear model") + 
    theme_bw() +
    theme(text = element_text(size=20),
          axis.text = element_text(size=18),
          axis.title = element_text(size=25),
          plot.title = element_text(size=30))
  
  set.seed(123)
  pvip_cart <- vip(my_model[[2]], method="permute", train=data_train_list[[1]], target=my_responsevar, 
                   metric="rsq", pred_wrapper=predict, nsim=30, geom="boxplot",
                   aesthetics = list(fill = "orange", color="black")) + 
    labs(title="Decision Tree") + 
    theme_bw() +
    theme(text = element_text(size=20),
          axis.text = element_text(size=18),
          axis.title = element_text(size=25),
          plot.title = element_text(size=30))
  
  
  set.seed(123)
  pvip_rf <- vip(my_model[[3]], method="permute",train=data_train_list[[1]], target=my_responsevar, 
                 metric="rsq", pred_wrapper=predict, nsim=30, geom="boxplot",
                 aesthetics = list(fill = "#068DA9", color="black")) + 
    labs(title=my_responsevar) + 
    theme_bw() +
    theme(text = element_text(size=20),
          axis.text = element_text(size=18),
          axis.title = element_text(size=25),
          plot.title = element_text(size=30))
  
  
  set.seed(123)
  pvip_gbm <- vip(my_model[[4]], method="permute", train=data_train_list[[1]], target=my_responsevar, 
                  metric="rsq", pred_wrapper=predict, nsim=30, geom="boxplot",
                  aesthetics = list(fill = "darkblue", color="black")) + 
    labs(title="Gradient Boosting") + 
    theme_bw() +
    theme(text = element_text(size=18),
          axis.text = element_text(size=20),
          axis.title = element_text(size=25),
          plot.title = element_text(size=30))
  
  
  # Combined plots
  plot_pvip_all <- plot_grid(pvip_lm, pvip_cart, pvip_rf, pvip_gbm,
                             labels = c("A", "B", "C", "D"),
                             ncol = 2,
                             label_size = 16)
  
  # Save the combined plot as PNG
 # ggsave(filename = file.path(paste0("png/vip_plot_", my_responsevar, ".png")), 
#         plot = plot_pvip_all, 
#         width = 12, height = 10, dpi = 300)
  
  # Create a list to store the objects
  output <- list(
    plot_pvip_all = plot_pvip_all,
    pvip_lm = pvip_lm,
    pvip_cart = pvip_cart,
    pvip_rf = pvip_rf,
    pvip_gbm = pvip_gbm
  )
  
  return(output)
}
```


```{r, warning=FALSE}
# Use vip function 
# select the model with the best performance and lowest MAE
vip_1 <- vip_plots(crop_models_list[[4]]$formula1, "cropPC1", "1")
vip_2 <- vip_plots(crop_models_list[[4]]$formula2, "cropPC2", "2")
vip_3 <- vip_plots(crop_models_list[[4]]$formula3, "crop_rot_rich", "3")
vip_4 <- vip_plots(crop_models_list[[4]]$formula4, "crop_rot_SDI", "4")
vip_5 <- vip_plots(crop_models_list[[4]]$formula5, "crop_sp_rich", "5")
vip_6 <- vip_plots(crop_models_list[[4]]$formula6, "crop_sp_SDI", "6")
```


```{r, fig.width = 14, fig.height=18}
vip_1$plot_pvip_all
vip_2$plot_pvip_all
vip_3$plot_pvip_all
vip_4$plot_pvip_all
vip_5$plot_pvip_all
vip_6$plot_pvip_all
```


```{r, fig.width = 14, fig.height=30, eval = F}
# Appendix figure
vip_rf <- plot_grid(vip_1$pvip_rf, vip_1$pvip_lm, 
                    vip_2$pvip_rf, vip_2$pvip_lm,
                    vip_3$pvip_rf, vip_3$pvip_lm,
                    vip_4$pvip_rf, vip_4$pvip_lm,
                    vip_5$pvip_rf, vip_5$pvip_lm,
                    vip_6$pvip_rf, vip_6$pvip_lm,
          labels = c("A", "B", "C", "D", "E", "F", 
                     "G", "H", "I", "J", "K", "L"),
          ncol = 2,
          nrow = 6,
          label_size = 16)

vip_rf
```


```{r, fig.width = 14, fig.height=30}
getwd()
setwd("D:/Josi/PhD/CrossDIV/WP1.2_Method/WP1.2_Method_Data/R Scripts/4_IACS_Betriebe_exploration/output_files/ML_output_20241030")
#ggsave("png/20250305_vip_rf3.png", vip_rf, width = 14, height = 18, dpi = 1200)
#ggsave("png/20250305_vip_rf3.pdf", vip_rf, width = 14, height = 18, dpi = 1200)
```


```{r, fig.width = 14, fig.height=18}
# Appendix figure
vip_rfa <- plot_grid(vip_1$pvip_rf, vip_1$pvip_lm, 
                    vip_2$pvip_rf, vip_2$pvip_lm,
                    vip_3$pvip_rf, vip_3$pvip_lm,
          labels = c("a", "b", "c", "d", "e", "f"),
          ncol = 2,
          nrow = 3,
          label_size = 16)

vip_rfa
```


```{r, fig.width = 14, fig.height=18}
setwd("D:/Josi/PhD/CrossDIV/WP1.2_Method/WP1.2_Method_Data/R Scripts/4_IACS_Betriebe_exploration/output_files/ML_output_20241030")
ggsave("png/20250305_vip_rf3a.png", vip_rfa, width = 14, height = 18, dpi = 1200)
ggsave("png/20250305_vip_rf3a.pdf", vip_rfa, width = 14, height = 18, dpi = 1200)
```


```{r, fig.width = 14, fig.height=18}
vip_rfb <- plot_grid(vip_4$pvip_rf, vip_4$pvip_lm,
                     vip_5$pvip_rf, vip_5$pvip_lm,
                     vip_6$pvip_rf, vip_6$pvip_lm,
          labels = c("g", "h", "i", "j", "k", "l"),
          ncol = 2,
          nrow = 3,
          label_size = 16)

vip_rfb
```


```{r, fig.width = 14, fig.height=18}
setwd("D:/Josi/PhD/CrossDIV/WP1.2_Method/WP1.2_Method_Data/R Scripts/4_IACS_Betriebe_exploration/output_files/ML_output_20241030")
#ggsave("png/20250305_vip_rf3b.png", vip_rfb, width = 14, height = 18, dpi = 1200)
#ggsave("png/20250305_vip_rf3b.pdf", vip_rfb, width = 14, height = 18, dpi = 1200)

```


```{r, fig.width = 14, fig.height=10}
# for public: Plot VIP for Random Forest only for PC1 and PC2
vip_rf_pc1 <- vip_1$pvip_rf + 
  ggtitle("a) PC1") +
  theme_bw(base_size = 20) +
  theme(panel.grid = element_blank(),
    #    axis.ticks = element_blank(),
        legend.position = "bottom",
        plot.title = element_text(size = 26),
        legend.title = element_text(size = 24), 
        legend.text = element_text(size = 20)) 

vip_rf_pc2 <- vip_2$pvip_rf + 
  ggtitle("b) PC2") +
  theme_bw(base_size = 20) +
  theme(panel.grid = element_blank(),
    #    axis.ticks = element_blank(),
        legend.position = "bottom", 
        plot.title = element_text(size = 26),
        legend.title = element_text(size = 24),
        legend.text = element_text(size = 20)) 

# Combine plots using grid.arrange
rf_combined <- grid.arrange(vip_rf_pc1, vip_rf_pc2, ncol = 2)
rf_combined
```


```{r, fig.width = 14, fig.height=10}
# Save combined plot
#ggsave("png/20250121_vip_rf_PC1_PC2.png", rf_combined, width = 12, height = 6, dpi = 1200)
#ggsave("png/20250121_vip_rf_PC1_PC2.pdf", rf_combined, width = 12, height = 6, dpi = 1200)

# Save as SVG
#svg("png/20250121_vip_rf_PC1_PC2.svg", width=12, height=6)
grid.arrange(vip_rf_pc1, vip_rf_pc2, ncol = 2)
#dev.off()

# Save as PDF
#pdf("png/20250121_vip_rf_PC1_PC2.pdf", width=12, height=6)
#grid.arrange(vip_rf_pc1, vip_rf_pc2, ncol = 2)
#dev.off()
```


```{r}
# Function to create PDP plots
pdp_plots <- function(my_models, my_var, algorithm = "Random Forests"){
  
  # Select the model based on the algorithm
  model_index <- switch(algorithm,
                        "GLM" = 1,
                        "Decision Tree" = 2,
                        "Random Forests" = 3,
                        "Gradient Boosting" = 4)
  
  # Most important variable
  pdp_var1 <- my_models[[model_index]] %>%  
    partial(pred.var=c(my_var), approx=T) %>% 
    cbind(., algorithm = algorithm)
  
  # Plot
  Fig05a <- ggplot(pdp_var1, aes(x = .data[[my_var]], y = yhat, color = algorithm)) +
    geom_line(size = 1) +
    scale_color_manual(values = c("GLM" = "grey", 
                                  "Decision Tree" = "orange", 
                                  "Random Forests" = "#068DA9", 
                                  "Gradient Boosting" = "darkblue")) +
    ylab("PD") +
    xlab("") +
    theme_bw() +
    theme(legend.position = "none",
          panel.grid = element_blank(),
          panel.border = element_blank(),
          axis.line.x = element_line(color = "black"),
          axis.line.y = element_line(color = "black"),
          axis.text = element_text(size = 12),  # Keep axis text
         axis.title = element_text(size = 16))
          
  output <- list(pdp_var1 = pdp_var1, plot = Fig05a)
  return(output)
}
```


```{r}
# -----------------------------------------------------------------------------

# Create list to store PDP plots for each formula

# -----------------------------------------------------------------------------

# select top important variables

# Function to get top 3 important variables for Random Forest models
get_top_variables <- function(model) {
  var_imp <- varImp(model)$importance
  var_imp_sorted <- var_imp[order(var_imp$Overall, decreasing = TRUE), , drop = FALSE]
  return(rownames(var_imp_sorted)[1:3])
}
```


```{r}
# Get top 3 variables for each formula's Random Forest model
formula_names <- paste0("formula", 1:6)
top_vars <- list()

for (formula_name in formula_names) {
  rf_model <- crop_models_list[[4]][[formula_name]]$model.rf
  top_vars[[formula_name]] <- get_top_variables(rf_model)
  
  # Print results
  cat("\nTop 3 important variables for", formula_name, ":\n")
  print(top_vars[[formula_name]])
}
```


```{r}
# careful: some variable deviate from the VIP plot. The need to be changed manually
top_vars$formula2[2] <- "DGM_range"
top_vars$formula5[2] <- "crop_f_SDI"
top_vars$formula5[3] <- "crop_rot_SDI"

top_vars$formula1[3] <- "Field_size_mean_ha"
top_vars$formula1[2] <- "habitat_AREA_MEAN"

top_vars$formula3[1] <- "crop_f_SDI"
top_vars$formula3[3] <- "crop_sp_SDI"

top_vars$formula5[1] <- "crop_f_SDI"
top_vars$formula5[2] <-  "Number_farms"
```


```{r}
# Create list to store PDP plots for each formula

#RF

pdp_plots_list <- list()
formula_plots_list <- list()
#formula_plots <- list()

# Create PDP plots for each formula using top variables
for (formula_name in names(top_vars)) {
  pdp_plots_list[[formula_name]] <- list() #pdp list
  hist_plots_list <- list() #hist list
  
  # Create plots for each top variable in the formula
  for (var in top_vars[[formula_name]]) {
    # Create PDP plot
    pdp_plots_list[[formula_name]][[var]] <- pdp_plots(
      crop_models_list[[4]][[formula_name]], 
      var, 
      "Random Forests"
    ) 
    
    # Create histogram plot
    hist_plots_list[[var]] <- ggplot(data_train_list[[4]], aes(x = .data[[var]])) +
      geom_histogram(binwidth = (max(data_train_list[[4]][[var]]) - min(data_train_list[[4]][[var]])) / 20,
                    fill = "grey", color = "white") +
      labs(x = var, y = "Count") +  
      theme_bw() +
      theme(legend.position = "none",
            panel.grid = element_blank(),
            panel.border = element_blank(),
            axis.line.x = element_line(color = "black"),
            axis.line.y = element_line(color = "black"),
            axis.text = element_text(size = 12),  # Keep axis text
            axis.title = element_text(size = 16))
  }
  # Combine PDP plots for this formula
  pdp_plots_combined <- plot_grid(
    plotlist = lapply(pdp_plots_list[[formula_name]], function(x) x$plot),
    ncol = length(top_vars[[formula_name]]),
    labels = LETTERS[1:length(top_vars[[formula_name]])]
  )
  
  # Combine histogram plots
  hist_plots_combined <- plot_grid(
    plotlist = hist_plots_list,
    ncol = length(top_vars[[formula_name]])#,http://127.0.0.1:12539/graphics/plot_zoom_png?width=2560&height=1378
    #labels = letters[1:length(top_vars[[formula_name]])]
  )
  

  # Combine PDP and histogram plots vertically and store in list
  formula_plots_list[[formula_name]] <- plot_grid(
    pdp_plots_combined,
    hist_plots_combined,
    ncol = 1,
    rel_heights = c(1, 0.5)
  )
  
  # Save combined plot for this formula
  #ggsave(
   # filename = file.path("png", paste0("pdp_plots_with_hist_", formula_name, ".png")),
  #  plot = formula_plots,
  #  width = 4 * length(top_vars[[formula_name]]),
  #  height = 9,
  #  dpi = 300
  #)
}
```


```{r, fig.width = 14, fig.height=40}
pdp_ms <- plot_grid(
  plotlist = lapply(formula_plots_list, function(x) x),
  ncol = 1#,
 # labels = LETTERS[1:length(formula_plots_list)]
)
pdp_ms


```


```{r}
getwd()
setwd("D:/Josi/PhD/CrossDIV/WP1.2_Method/WP1.2_Method_Data/R Scripts/4_IACS_Betriebe_exploration/output_files/ML_output_20241030")


#svg("png/PC_PDP.svg", width=9, height=8)
grid.arrange(formula_plots_list[[1]] + ggtitle("a) PC1"), 
            formula_plots_list[[2]] + ggtitle("b) PC2"), 
            ncol=1,
            heights=c(1, 1),
            padding=unit(2, "cm"))
#dev.off()

#pdf("png/PC_PDP.pdf", width=9, height=8)
#grid.arrange(formula_plots_list[[1]] + ggtitle("a) PC1"), 
#             formula_plots_list[[2]] + ggtitle("b) PC2"), 
#             ncol=1,
#             heights=c(1, 1),
#             padding=unit(2, "cm"))
#dev.off()


# Save combined plot for all formulas
#ggsave(
#  filename = file.path("png", "20250405_pdp_plots_with_hist_all_formulas.png"),
#  plot = pdp_ms,
#  width = 15,
#  height = 24,
#  dpi = 1200
#)

#pdf("png/20250405_pdp_plots_with_hist_all_formulas.pdf", width=15, height=24)
#pdp_ms
#dev.off()
```


```{r}
# figure for main manuscript


# LM

top_var_lm <- list(
  formula1 = c("crop_f_SDI", "Field_size_mean_ha", "Number_farms"),
  formula2 = c("crop_f_SDI", "prop_oeko_farms", "habitat_EDGE_DENSITY"),
  formula3 = c("prop_oeko_farms", "crop_sp_SDI", "x_coord"),
  formula4 = c("prop_oeko_farms", "Field_size_mean_ha","crop_sp_SDI"),
  formula5 = top_vars$formula5,
  formula6 = top_vars$formula6)

colnames(df_model)
```


```{r}
pdp_plots_list <- list()
formula_plots_list <- list()
#formula_plots <- list()
```


```{r}
# Create PDP plots for each formula using top variables
for (formula_name in names(top_var_lm)) {
  pdp_plots_list[[formula_name]] <- list() #pdp list
  hist_plots_list <- list() #hist list
  
  # Create plots for each top variable in the formula
  for (var in top_var_lm[[formula_name]]) {
    # Create PDP plot
    pdp_plots_list[[formula_name]][[var]] <- pdp_plots(
      crop_models_list[[4]][[formula_name]], 
      var, 
      "GLM"
    ) 
    
    # Create histogram plot
    hist_plots_list[[var]] <- ggplot(data_train_list[[4]], aes(x = .data[[var]])) +
      geom_histogram(binwidth = (max(data_train_list[[4]][[var]]) - min(data_train_list[[4]][[var]])) / 30,
                     fill = "#068DA9", color = "white") +
      labs(x = var, y = "Count", size = 14) +  # Increased font size for axis labels
      theme_bw() +
      theme(panel.background = element_rect(fill = "white"),
            plot.background = element_rect(fill = "white"),
            axis.text = element_text(size = 12),  # Increased font size for axis text
            axis.title = element_text(size = 20), # Increased font size for axis titles
            plot.title = element_text(size = 16)) # Increased font size for plot title
  }
  
  # Combine PDP plots for this formula
  pdp_plots_combined <- plot_grid(
    plotlist = lapply(pdp_plots_list[[formula_name]], function(x) x$plot),
    ncol = length(top_vars[[formula_name]]),
    labels = LETTERS[1:length(top_vars[[formula_name]])]
  )
  
  # Combine histogram plots
  hist_plots_combined <- plot_grid(
    plotlist = hist_plots_list,
    ncol = length(top_vars[[formula_name]]),
    labels = letters[1:length(top_vars[[formula_name]])]
  )
  
  
  # Combine PDP and histogram plots vertically and store in list
  formula_plots_list[[formula_name]] <- plot_grid(
    pdp_plots_combined,
    hist_plots_combined,
    ncol = 1,
    rel_heights = c(1, 0.5)
  )
  
  # Save combined plot for this formula
  #ggsave(
  # filename = file.path("png", paste0("pdp_plots_with_hist_", formula_name, ".png")),
  #  plot = formula_plots,
  #  width = 4 * length(top_vars[[formula_name]]),
  #  height = 9,
  #  dpi = 300
  #)
}
```


```{r, fig.width = 14, fig.height=40}
pdp_ms <- plot_grid(
  plotlist = lapply(formula_plots_list, function(x) x),
  ncol = 1,
  labels = LETTERS[1:length(formula_plots_list)]
)
pdp_ms
```


```{r}
# Save combined plot for all formulas
#ggsave(
#  filename = file.path("png", "pdp_plots_with_hist_all_formulas_LM.png"),
#  plot = pdp_ms,
#  width = 15,
#  height = 24,
#  dpi = 1200
#)
```
